### ISSUE TITLE
Need merge of official repo and hackage upload

### ISSUE THREAD

**Issue by ddssff** [ddssff/listlike#1]

**Comment by ddssff** [comment]
Would you like someone else to take over maintenance of ListLike on hackage?

**Comment by JohnLato** [comment]
If someone is regularly using it and willing, I don't mind. I don't have
quite as much time for Haskell these days, so my response time is generally
measured in weeks.

If you're volunteering I'll add you as a maintainer.

**Comment by ddssff** [comment]
I am so volunteering!  That would be great.  Hackage account https://hackage.haskell.org/user/DavidFox.

**Comment by JohnLato** [comment]
Apologies for delay, I guess it's just evidence that this is needed (although I am on vacation now).  DavidFox added to hackage maintainers.  Looks like you have an updated repo, could you please do the hackage upload?

**Comment by ddssff** [comment]
Yes, will do.

**Comment by ddssff** [comment]
Hackage upload done.
