### ISSUE TITLE
`tail` in the `DList` instance is not efficient

### ISSUE THREAD

**Issue by andreasabel** [ddssff/listlike#14]
`tail :: DList a -> DList a` is essentially `DList.fromList . Data.List.tail . DList.toList` in dlist-1.0, which is losing efficiency over `(Data.List.tail .)`. The latter cannot be implemented outside of `dlist` though, due to data abstraction.
 
See https://github.com/ddssff/listlike/commit/8c207801493dfed59599616b4d157ee105ead363#r55694269 and https://github.com/spl/dlist/issues/98.

**Comment by spl** [comment]
A couple of things:
* As I mentioned on <https://github.com/spl/dlist/issues/98>, I changed `tail` to the current one since the previous `tail` was inefficient, and I think the current one is slightly better than `toList . tail`. The `listlike` implementation of `tail` is the same as the previous `dlist` implementation.
* You could use the `UnsafeDList` approach, that @andreasabel mentioned, in `listlike`. I don't like it myself, but the option is there and perfectly acceptable.

**Comment by andreasabel** [comment]
@spl wrote:
> * You could use the `UnsafeDList` approach, that @andreasabel mentioned, in `listlike`. I don't like it myself, but the option is there and perfectly acceptable.

I don't think this is an option here because the constructor for `DList` is not exported ("data abstraction").

**Comment by spl** [comment]
> I don't think this is an option here because the constructor for `DList` is not exported ("data abstraction").

It's exported from `Data.DList.Internal`.

**Comment by andreasabel** [comment]
@spl: I tried `import Data.DList.Internal (DList(..))` but this gives me
```
src/Data/ListLike/DList.hs:11:1: error:
    Could not load module ‘Data.DList.Internal’
    it is a hidden module in the package ‘dlist-1.0’
```
That's to be expected when looking at the docs at https://hackage.haskell.org/package/dlist-1.0:
```
Modules
Data
Data.DList
Data.DList.DNonEmpty
Data.DList.Unsafe
```
(That's also the convention: `Internal` modules are not exported.)

**Comment by spl** [comment]
@andreasabel Sorry, I misremembered. Use `Data.DList.Unsafe`. It's been over a year since I did it. And I surprised myself to find that I actually have a test for that.

**Comment by spl** [comment]
@andreasabel Also, there's documentation on this under the heading of Abstraction at the link you provided: <https://hackage.haskell.org/package/dlist-1.0>.

**Comment by andreasabel** [comment]
> @andreasabel Sorry, I misremembered. Use `Data.DList.Unsafe`. It's been over a year since I did it. And I surprised myself to find that I actually have a test for that.

Thanks for the guidance.  I'll use this backdoor, then.

> @andreasabel Also, there's documentation on this under the heading of Abstraction at the link you provided: https://hackage.haskell.org/package/dlist-1.0.

Thanks, I see this.  (Actually, I do not want to do anything unsafe, the `(Data.List.tail .)` function does not break the invariant mentioned there.)

There is still a problem with accessing the documentation of `Data.List.Unsafe`, see https://github.com/spl/dlist/issues/100.
