### ISSUE TITLE
ListLike 4.7.8 has no tag

### ISSUE THREAD

**Issue by andreasabel** [ddssff/listlike#22]
David @ddssff , please add a tag for 4.7.8.

**Comment by ddssff** [comment]
I will do my best.   `git tag -a -m 'v4.7.8' v4.7.8` ?

**Comment by andreasabel** [comment]
Maybe follow the scheme of the latest tags:
```
-a          -m
v4.7.4      Released ListLike-4.7.4 to hackage
v4.7.6      Released ListLike-4.7.6 to hackage
v4.7.7      Released ListLike-4.7.7 to hackage
```

**Comment by ddssff** [comment]
I tried `git tag -a v4.7.8 -m 'Released ListLike-4.7.8 to hackage'` followed by a push but it had no effect.  If you are able to do this it would be appreciated.

**Comment by andreasabel** [comment]
Yeah, pushing tags is awkward with git; it is one of:
1. `git push --tags`
2. `git push --follow-tags`  (this one pushes commits and tags in one go if needed)

**Comment by ddssff** [comment]
Done, thanks.
