### ISSUE TITLE
ListLike gets stuck in tests on GHC 9.2.5 and 9.4.3 [GHC regression!]

### ISSUE THREAD

**Issue by lf-** [ddssff/listlike#23]
Hi! I'm filing this issue as a placeholder to direct people to the upstream GHC bug here: https://gitlab.haskell.org/ghc/ghc/-/issues/22425

This is confusing a fair number of nixpkgs users so I want to make this easier to find.

The solution in nixpkgs is to use `haskell.lib.dontCheck` in an overlay. Here's some Nix code from a project of mine to achieve that, if that's useful: https://github.com/lf-/hsfixit/blob/6c8275906a911b9caee58b5dd002fcca18224259/flake.nix#L113-L114

No action is needed; nothing is wrong with ListLike itself (although I would appreciate the issue getting pinned!)

**Comment by andreasabel** [comment]
@lf- wrote:
> placeholder to direct people to the upstream GHC bug here: https://gitlab.haskell.org/ghc/ghc/-/issues/22425

This GHC issue is fixed in later releases of 9.2 and 9.4.

Can we close this issue here now?
