### ISSUE TITLE
Unfork this repo

### ISSUE THREAD

**Issue by andreasabel** [ddssff/listlike#27]
@ddssff : This repo is still declared as a fork of https://github.com/JohnLato/listlike , so, whenever I open a PR here it is by default opened against this parent repo.   Solutions I think of:

1. Unfork this repo in the settings.  If you give me admin permissions to this repo, I can do it myself.
2. Transfer the repo to its own new organization, e.g. `haskell-listlike`.  Transfering also needs admin-powers.  
   Model for this: https://github.com/blaze-builder

**Comment by ddssff** [comment]
I went into Settings -> Collaborators but there is no role dropdown in the Manage Access table.  :-(

**Comment by andreasabel** [comment]
Ok, maybe I cannot become admin for a repo on your private account.

I tried to unfork ("Extract") the repo at https://support.github.com/request following this recipe: https://ralphjsmit.com/unfork-github-repo

I couldn't do it, the bot said:
> It looks like either ddssff/listlike doesn't exist or you are not an admin, only an admin can make this request.

But you should be able to do it.

<img width="608" alt="Screenshot 2023-02-20 at 11 12 30" src="https://user-images.githubusercontent.com/1155218/220076685-20384e6f-f37b-4f3f-b3ba-2b9d107b0f84.png">

**Comment by ddssff** [comment]
I will give it a shot.  Happy to make you an admin wherever, move the repo, whatever works.

**Comment by andreasabel** [comment]
@ddssff Any luck with  https://support.github.com/request  ?

**Comment by ddssff** [comment]
I think I did it.
