### ISSUE TITLE
Repo links to non-existing wiki

### ISSUE THREAD

**Issue by andreasabel** [ddssff/listlike#34]
<img width="267" alt="Screenshot 2023-09-01 at 06 15 44" src="https://github.com/ddssff/listlike/assets/1155218/f653fc9c-32d6-40e6-bf73-daddc1a916de">

This link is dead.

We should link instead to https://hackage.haskell.org/package/ListLike

@ddssff Only the repo owner can change this.

**Comment by ddssff** [comment]
Will do.
